# es la plantilla que el backend
# clic en "Desplegar". Se incluye aquí como referencia de lo que el código
# generaría dinámicamente en producción con kubernets, pero NO SE ESTA USANDO
apiVersion: v1
kind: Pod
metadata:
  name: honeypot-instance-PLACEHOLDER_ID
  labels:
    app: honeypot-instance
    honeypotId: "PLACEHOLDER_ID"
spec:
  containers:
    - name: honeypot
      image: honeypot-template:latest
      env:
        - name: HONEYPOT_ID
          value: "PLACEHOLDER_ID"
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: honeypot-PLACEHOLDER_ID-token
              key: token
        - name: BACKEND_URL
          value: "http://honey-backend-svc:4000"
  restartPolicy: Never
